const mongoose= require('mongoose');

const memberSchema= new mongoose.Schema({
    id:{
        type:Object,
        required:true,
        unique:true
    },
    membership:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    photo:{
        type:String,
    },
    fdocument:{
        type:String,
    },
    bdocument:{
        type:String,
    },
    gender:{
        type:String,
        required:true
    },
    dob:{
        type:String,
        required:true
    },
    contact:{
        type:Number,
        required:true
    },
    doj:{
        type:String,
        required:true
    },
    email:{
        type:String,
    },
    address1:{
        type:String,
        required:true
    },
    PhysicalCondition:{
        type:String,
        required:true
    },
    MedicalCondition:{
        type:String,
        required:true
    },
    centerlocation:{
        type:String,
        required:true
    },
    econtactn1:{
        type:String,
        required:true
    },
    econtactn2:{
        type:String,
    },
    relation1:{
        type:String,
        required:true
    },
    relation2:{
        type:String,
    },
    econtact1:{
        type:Number,
        required:true
    },
    econtact2:{
        type:Number,
    },
    isActive:{
        type:Boolean,
        default:true
    },
    version: {
        type: Number,
        default: 1,
      },
    receipt:[{type:mongoose.Types.ObjectId,ref:"RECEIPT",required:true}],
    
})
const Member= mongoose.model("MEMBER",memberSchema);
module.exports=Member;